-- Read-only verification for the TrialOps Snowflake foundation.

USE ROLE ACCOUNTADMIN;

SHOW ROLES LIKE 'CTOPS_TEAM_ROLE';
SHOW WAREHOUSES LIKE 'CTOPS_WH';
SHOW RESOURCE MONITORS LIKE 'CTOPS_WH_MONITOR';
SHOW DATABASES LIKE 'CTOPS_HACKATHON';
SHOW SCHEMAS IN DATABASE CTOPS_HACKATHON;
SHOW GRANTS TO ROLE CTOPS_TEAM_ROLE;
SHOW GRANTS OF ROLE CTOPS_TEAM_ROLE;
SHOW WORKSPACES LIKE 'TRIALOPS_SHARED' IN SCHEMA CTOPS_HACKATHON.COLLAB;

USE ROLE CTOPS_TEAM_ROLE;
USE WAREHOUSE CTOPS_WH;
USE DATABASE CTOPS_HACKATHON;
USE SCHEMA CORE;

SELECT
  CURRENT_USER() AS USER_NAME,
  CURRENT_ROLE() AS ACTIVE_ROLE,
  CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE,
  CURRENT_DATABASE() AS ACTIVE_DATABASE,
  CURRENT_SCHEMA() AS ACTIVE_SCHEMA,
  AI_COMPLETE('llama3.1-70b', 'Reply with exactly: CORTEX_READY')
    AS CORTEX_SMOKE_TEST;
