-- Run after TRIALOPS_SERVICE exists so team members can use its public endpoint.

USE ROLE CTOPS_TEAM_ROLE;
USE DATABASE CTOPS_HACKATHON;
USE SCHEMA APP;

GRANT SERVICE ROLE TRIALOPS_SERVICE!ALL_ENDPOINTS_USAGE TO ROLE CTOPS_TEAM_ROLE;

SHOW ENDPOINTS IN SERVICE TRIALOPS_SERVICE;
