-- ATLAS — Advanced Trial Lifecycle & Analytics System: shared Snowflake foundation
-- Run with: snow sql -c hackathon -f snowflake/migrations/001_foundation.sql

USE ROLE ACCOUNTADMIN;

-- 1. Shared least-privilege role and role hierarchy.
CREATE ROLE IF NOT EXISTS CTOPS_TEAM_ROLE
  COMMENT = 'Shared development role for the ATLAS PS-04 hackathon project';

GRANT ROLE CTOPS_TEAM_ROLE TO ROLE SYSADMIN;
GRANT ROLE CTOPS_TEAM_ROLE TO USER AGNIBHA;
GRANT ROLE CTOPS_TEAM_ROLE TO USER "SIMRAN.SAH";
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CTOPS_TEAM_ROLE;
GRANT USE AI FUNCTIONS ON ACCOUNT TO ROLE CTOPS_TEAM_ROLE;

-- 2. Cost-controlled compute dedicated to the project.
CREATE WAREHOUSE IF NOT EXISTS CTOPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 1
  SCALING_POLICY = 'STANDARD'
  COMMENT = 'Extra-small auto-suspending compute for ATLAS development';

CREATE RESOURCE MONITOR IF NOT EXISTS CTOPS_WH_MONITOR
  WITH CREDIT_QUOTA = 25
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 80 PERCENT DO SUSPEND
    ON 90 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE CTOPS_WH SET RESOURCE_MONITOR = CTOPS_WH_MONITOR;
GRANT USAGE ON WAREHOUSE CTOPS_WH TO ROLE CTOPS_TEAM_ROLE;

-- 3. One governed database, separated by data lifecycle and responsibility.
CREATE DATABASE IF NOT EXISTS CTOPS_HACKATHON
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'Governed Snowflake data plane for ATLAS — Advanced Trial Lifecycle & Analytics System';

CREATE SCHEMA IF NOT EXISTS CTOPS_HACKATHON.RAW
  COMMENT = 'Immutable source protocol, clause, note, lab, and synthetic patient inputs';
CREATE SCHEMA IF NOT EXISTS CTOPS_HACKATHON.CORE
  COMMENT = 'Normalized criteria, evidence, deterministic screening results, tasks, and audit events';
CREATE SCHEMA IF NOT EXISTS CTOPS_HACKATHON.AI
  COMMENT = 'Cortex Search services, validated model outputs, and AI observability';
CREATE SCHEMA IF NOT EXISTS CTOPS_HACKATHON.APP
  COMMENT = 'Backend-facing views, functions, procedures, and orchestration objects';
CREATE SCHEMA IF NOT EXISTS CTOPS_HACKATHON.COLLAB
  COMMENT = 'Shared Snowflake Workspace and collaboration assets';

GRANT USAGE ON DATABASE CTOPS_HACKATHON TO ROLE CTOPS_TEAM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CTOPS_HACKATHON TO ROLE CTOPS_TEAM_ROLE;

-- RAW: loaders can land public protocol and synthetic evidence inputs.
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA CTOPS_HACKATHON.RAW TO ROLE CTOPS_TEAM_ROLE;

-- CORE: deterministic, governed operational state.
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE, CREATE SEQUENCE, CREATE STREAM
  ON SCHEMA CTOPS_HACKATHON.CORE TO ROLE CTOPS_TEAM_ROLE;

-- AI: grounded retrieval and validated Cortex outputs.
GRANT CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE CORTEX SEARCH SERVICE
  ON SCHEMA CTOPS_HACKATHON.AI TO ROLE CTOPS_TEAM_ROLE;

-- APP: stable interfaces consumed by the FastAPI backend.
GRANT CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE STREAM, CREATE TASK
  ON SCHEMA CTOPS_HACKATHON.APP TO ROLE CTOPS_TEAM_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CTOPS_TEAM_ROLE;

-- COLLAB: shared Snowflake Workspace only; application data stays elsewhere.
GRANT CREATE WORKSPACE
  ON SCHEMA CTOPS_HACKATHON.COLLAB TO ROLE CTOPS_TEAM_ROLE;

-- 4. Make the project context explicit for subsequent migrations.
USE ROLE CTOPS_TEAM_ROLE;
USE WAREHOUSE CTOPS_WH;
USE DATABASE CTOPS_HACKATHON;
USE SCHEMA CORE;

SELECT
  CURRENT_ROLE() AS ACTIVE_ROLE,
  CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE,
  CURRENT_DATABASE() AS ACTIVE_DATABASE,
  CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
