-- One-time, least-privilege Snowpark Container Services deployment objects.

USE ROLE ACCOUNTADMIN;
CREATE COMPUTE POOL IF NOT EXISTS CTOPS_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Small auto-suspending pool for the TrialOps hackathon web service';

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE CTOPS_TEAM_ROLE;
GRANT USAGE, MONITOR ON COMPUTE POOL CTOPS_COMPUTE_POOL TO ROLE CTOPS_TEAM_ROLE;
GRANT CREATE IMAGE REPOSITORY, CREATE SERVICE
  ON SCHEMA CTOPS_HACKATHON.APP TO ROLE CTOPS_TEAM_ROLE;

USE ROLE CTOPS_TEAM_ROLE;
USE DATABASE CTOPS_HACKATHON;
USE SCHEMA APP;

CREATE IMAGE REPOSITORY IF NOT EXISTS TRIALOPS_REPOSITORY
  COMMENT = 'OCI images for the TrialOps Evidence Desk web application';
